"use client";

import { useSearchParams } from "next/navigation";

export const Header = () => {
    const searchParams = useSearchParams();

    const title = "Playing " + (searchParams.get("title") || "Game");

    return (
        <head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
            ></meta>
            <link rel="icon" href="/webplay/favicon.ico" />
        </head>
    );
};
